// USER
// login/signup
export const USER_LOGIN = "USER_LOGIN";
export const USER_SIGNUP = "USER_SIGNUP";
export const USER_SET_TOKEN = "USER_SET_TOKEN";

// update
export const USER_UPDATE = "USER_UPDATE";
// delete
export const USER_DELETE = "USER_DELETE";
export const USER_DELETE_SHOW_MODAL = "USER_DELETE_SHOW_MODAL";
// profile View
export const USER_SHOW_DATA = "USER_SHOW_DATA";
export const USER_SHOW_FAV_MOVIE_LIST = "USER_SHOW_FAV_MOVIE_LIST";
export const USER_TOGGLE_FAV_MOVIE = "USER_TOGGLE_FAV_MOVIE";
export const USER_SET = "USER_SET"; // fetch the user
export const USER_SET_DATA = "USER_SET_DATA";
export const USER_SET_USERNAME = "USER_SET_USERNAME";
export const USER_SET_PASSWORD = "USER_SET_PASSWORD";
export const USER_SET_EMAIL = "USER_SET_EMAIL";
export const USER_SET_BIRTHDAY = "USER_SET_BIRTHDAY";
export const USER_SET_FAVOURITE_MOVIES = "USER_SET_FAVOURITE_MOVIES";

// MOVIES
export const MOVIES_SET = "MOVIES_SET"; // fetch all Movies
export const MOVIES_SHOW_FILTERED_MOVIES = "MOVIES_SHOW_FILTERED_MOVIES";
// export const MOVIES_SET_SEARCH_QUERY = "MOVIES_SET_SEARCH_QUERY";

// needed?
export const SHOW_GENRE_DESCRIPTION = "SHOW_GENRE_DESCRIPTION";
export const SHOW_DIRECTOR_BIO = "SHOW_DIRECTOR_BIO";
export const SET_USER_FROM_LOCALSTORAGE = "SET_USER_FROM_LOCALSTORAGE";
export const SET_TOKEN_FROM_LOCALSTORAGE = "SET_TOKEN_FROM_LOCALSTORAGE";
